# -*- coding: utf-8 -*-
"""Project 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W3qarOZ0eix32chaOKsVTuSVj4iiX87L
"""

pip install requests beautifulsoup4 pandas

import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime

# URL của trang CoinMarketCap
url = 'https://coinmarketcap.com/'

# Gửi yêu cầu đến trang web
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

# Hàm để lấy thông tin về tiền điện tử
def get_crypto_data(crypto_name):
    # Tìm bảng chứa thông tin các đồng tiền điện tử
    table = soup.find('table', {'class': 'cmc-table'})

    # Tìm các hàng trong bảng
    rows = table.find_all('tr')

    # Duyệt qua các hàng để tìm thông tin của đồng tiền cụ thể
    for row in rows:
        if crypto_name.lower() in row.text.lower():
            columns = row.find_all('td')
            price = columns[3].text.strip()
            hour_change = columns[4].text.strip()
            day_change = columns[5].text.strip()
            week_change = columns[6].text.strip()
            market_cap = columns[7].text.strip()
            volume = columns[8].text.strip()

            return {
                'Crypto Name': crypto_name,
                'Price': price,
                '1h %': hour_change,
                '24h %': day_change,
                '7d %': week_change,
                'Market Cap': market_cap,
                '24h Volume': volume,
                'Timestamp': datetime.now()
            }

    return None

# Lấy thông tin cho Bitcoin, Ethereum và BNB
cryptos = ['Bitcoin', 'Ethereum', 'BNB']
data = []

for crypto in cryptos:
    crypto_data = get_crypto_data(crypto)
    if crypto_data:
        data.append(crypto_data)

# Tạo DataFrame từ dữ liệu thu thập được
df = pd.DataFrame(data)

# Hiển thị DataFrame
print(df)

# Lưu DataFrame vào file CSV
df.to_csv('crypto_data.csv', index=False)

