# Great work! But you should also parse the currencies' names because it currently contains the symbol of the currency.

# -*- coding: utf-8 -*-
"""trinh_8554_Project4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ddmVBEfBC3uZVsssM_eJpkI3IKTLKJ1J
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd

url = "https://coinmarketcap.com/"
page = requests.get(url)
soup = BeautifulSoup(page.text, "html")
print(soup)

table = soup.find("table", "sc-7b3ac367-3 etbcea cmc-table")
table

headers = table.find_all("th")
column_names = [header.text.strip() for header in headers]
print(column_names)

rows = table.find_all("tr")[1:]
table_data = []
for row in rows:
    cells = row.find_all("td")
    cell_data = [cell.text.strip() for cell in cells]
    table_data.append(cell_data)

df = pd.DataFrame(table_data, columns=[column_names])
df

df = df.drop(["Circulating Supply", "Last 7 Days"], axis=1)
df

df_csv = df.to_csv("coinmarketcap.csv", index=False)
