# -*- coding: utf-8 -*-
"""Project3_doan09801.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16tx5t1X1SLGDkTVHAJV_Q6jN6rlj3Bus
"""

import os
import shutil

path = '/Users/donlancy/Library/CloudStorage/OneDrive-Personal/Project_3'

list_ = os.listdir(path)

for file_ in list_:
	name, ext = os.path.splitext(file_)

	ext = ext[1:]

	if ext == '':
		continue

	if os.path.exists(path+'/'+ext):
		shutil.move(path+'/'+file_, path+'/'+ext+'/'+file_)
	else:
		os.makedirs(path+'/'+ext)
		shutil.move(path+'/'+file_, path+'/'+ext+'/'+file_)

# Review:
'''
Handle Edge Cases: Consider handling cases where the file might have multiple dots in the name (e.g., file.name.extension). The current approach correctly handles it by using os.path.splitext(file_) but be cautious of files with no extension.
Avoid Redundant Operations: If you extract the file's extension and check if it exists, this can be done only once before checking whether the directory already exists or not.
And remember that out project would require you to sort files into different file types. E.g: Documents: .pdf, .txt; Audio: .mp3, .av
'''