# -*- coding: utf-8 -*-
"""Note Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g-gTHyw_kXGKwoM1ROywe6itFBkjG-a_
"""

import os
import shutil

# Define the file types and corresponding folders
file_types = {
    'txt': 'TextFiles',
    'pdf': 'PDFs',
    'jpg': 'JPGImages',
    'png': 'PNGImages',
    'docx': 'WordFiles',
    'xlsx': 'ExcelFiles',
    'tsv': 'TSVFiles',
    'csv': 'CSVFiles',
    'ipynb': 'JupyterNotebooks'
}

# Create folders if they don't exist
for folder in file_types.values():
    if not os.path.exists(folder):
        os.makedirs(folder)

# Path to the directory containing files
source_dir = '/content/sample_data'

# Organize files
for file_name in os.listdir(source_dir):
    file_ext = file_name.split('.')[-1].lower()
    if file_ext in file_types:
        folder_name = file_types[file_ext]
        source_file = os.path.join(source_dir, file_name)
        destination_file = os.path.join(folder_name, file_name)
        shutil.move(source_file, destination_file)
        print(f'Moved {file_name} to {folder_name}.')
    else:
        print(f'There is no {file_name} file.')