# -*- coding: utf-8 -*-
"""Note Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g-gTHyw_kXGKwoM1ROywe6itFBkjG-a_
"""

import os
import shutil

# Define the file types and corresponding folders
file_types = {
    'txt': 'TextFiles',
    'pdf': 'PDFs',
    'jpg': 'JPGImages',
    'png': 'PNGImages',
    'docx': 'WordFiles',
    'xlsx': 'ExcelFiles',
    'tsv': 'TSVFiles',
    'csv': 'CSVFiles',
    'ipynb': 'JupyterNotebooks'
}

# Create folders if they don't exist
for folder in file_types.values():
    if not os.path.exists(folder):
        os.makedirs(folder)

# Path to the directory containing files
source_dir = '/content/sample_data'

# Organize files
for file_name in os.listdir(source_dir):
    file_ext = file_name.split('.')[-1].lower()
    if file_ext in file_types:
        folder_name = file_types[file_ext]
        source_file = os.path.join(source_dir, file_name)
        destination_file = os.path.join(folder_name, file_name)
        shutil.move(source_file, destination_file)
        print(f'Moved {file_name} to {folder_name}.')
    else:
        print(f'There is no {file_name} file.')

# Review:
'''
Handling Files without Extensions: The code assumes all files have extensions. However, if a file doesn't have an extension, it will throw an IndexError or misbehave.
Directory Path Handling: The destination path for moving files doesn't account for the fact that folder_name is being used as a relative path. This can lead to issues if folder_name isn't relative to the source_dir.
Redundant File Move Check: The else clause prints "There is no {file_name} file." for files that don't match any extension in file_types. This message might be misleading since it implies the file doesn't exist, when in fact, it just doesn't have a matching extension.
Destination Path Construction: The destination_file is constructed without a directory path, which may leading to incorrect file moves.
'''