# -*- coding: utf-8 -*-
"""Project 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mx_ielpC2Wgpl--PQirptt0jmeJff8ek
"""

!pip install gdown

import os
import shutil
import gdown

# Định nghĩa các loại tệp và thư mục đích
file_types = {
    "Images": [".jpg", ".png"],
    "Documents": [".pdf", ".docx", ".txt", ".tsv"],
    "Spreadsheets": [".csv", ".xlsx"],
    "Videos": [".mp4", ".avi"],
    "Compressed": [".zip", ".rar"],
    "Audio": [".mp3", ".wav"],
    "Executables": [".exe", ".msi"]
}

# URL Google Drive của thư mục nguồn
drive_url = "https://drive.google.com/drive/folders/1uJ9l8HAraB8p5sRj9b4FR1BA-Au24ykW?usp=sharing"
# Thư mục đích trên Colab
destination_folder = "/content/source_folder"

# Tạo thư mục đích nếu chưa tồn tại
os.makedirs(destination_folder, exist_ok=True)

# Tải tệp từ Google Drive
# gdown sẽ tự động tải các tệp trong thư mục Google Drive xuống thư mục đích
gdown.download_folder(drive_url, output=destination_folder)

# Tạo các thư mục đích nếu chúng chưa tồn tại
for folder in file_types.keys():
    os.makedirs(os.path.join(destination_folder, folder), exist_ok=True)

# Duyệt qua các tệp trong thư mục đích và sắp xếp chúng vào các thư mục tương ứng
for filename in os.listdir(destination_folder):
    file_path = os.path.join(destination_folder, filename)
    if os.path.isfile(file_path):
        file_extension = os.path.splitext(filename)[1].lower()
        for folder, extensions in file_types.items():
            if file_extension in extensions:
                shutil.move(file_path, os.path.join(destination_folder, folder, filename))
                break

print("Tệp đã được sắp xếp thành công!")