# -*- coding: utf-8 -*-
"""project_2 - Anh Phương.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10WHz5e5RNghOzKKmWbsm3IO0Jc_Cc0Ww
"""

def calculator():
    def add(x, y):
        return x + y

    def subtract(x, y):
        return x - y

    def multiply(x, y):
        return x * y

    def divide(x, y):
        return x / y

    def modulo(x, y):
        return x % y

    operations = {
        'A': add,
        'S': subtract,
        'M': multiply,
        'D': divide,
        'O': modulo
    }

    print("Enter 'A' for Addition.")
    print("Enter 'S' for Subtraction.")
    print("Enter 'M' for Multiplication.")
    print("Enter 'D' for Division.")
    print("Enter 'O' for Modulo.")

    choice = input("Enter Choice (A,S,M,D,O): ").upper()

    if choice in operations:
        try:
            num_1 = eval(input("Enter first number: "))
            num_2 = eval(input("Enter second number: "))

            if choice == 'D' and num_2 == 0:
                print("Error: Division by zero is not allowed.")
            else:
                result = operations[choice](num_1, num_2)
                if choice == 'A':
                    operation = '+'
                elif choice == 'S':
                    operation = '-'
                elif choice == 'M':
                    operation = '*'
                elif choice == 'D':
                    operation = '/'
                elif choice == 'O':
                    operation = '%'

                print(f"Result: {num_1} {operation} {num_2} = {result}")
        except ValueError:
            print("Error: Invalid input. Please enter numeric values.")
    else:
        print("Error: Invalid choice. Please enter A, S, M, D or O.")

calculator()

#You should utilize the eval() function more, since you have already used it.
#Keep up the good works!