# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sd2ZP2vPgJUK1fmnf78g23eNcnh6NjA1
"""

def calculate():
    print("Welcome to this calculator!")
    while True:
        #Enter numbers
        numbers = []
        while True:
            num = input('Enter a number (or type "done" to finish): ')
            if num.lower() == 'done':
                if len(numbers) < 2:
                    print('Please enter at least two numbers.')
                else:
                    break
            else:
                try:
                    numbers.append(float(num))
                except ValueError:
                    print('Invalid input. Please enter a valid number or type "done" to finish.')

        #Enter operations
        operations = []
        print('Available operations:')
        print(' + for Addition')
        print(' - for Subtraction')
        print(' * for Multiplication')
        print(' / for Division')
        print(' % for Modulus')

        while len(operations) < len(numbers) - 1:
            operation = input(f'Enter the operation {len(operations) + 1}/{len(numbers) - 1}: ')
            if operation in ['+', '-', '*', '/', '%']:
                operations.append(operation)
            else:
                print('Invalid operation. Please enter one of the available operations above.')

        #Calculate
        result = numbers[0]
        calculation_result = str(numbers[0])
        for i in range(1, len(numbers)):
            if operations[i - 1] == '+':
                result += numbers[i]
                calculation_result += f' + {numbers[i]}'
            elif operations[i - 1] == '-':
                result -= numbers[i]
                calculation_result += f' - {numbers[i]}'
            elif operations[i - 1] == '*':
                result *= numbers[i]
                calculation_result += f' * {numbers[i]}'
            elif operations[i - 1] == '/':
                if numbers[i] == 0:
                    print('Error: Division by zero. Please restart the calculation.')
                    return
                result /= numbers[i]
                calculation_result += f' / {numbers[i]}'
            elif operations[i - 1] == '%':
                if numbers[i] == 0:
                    print('Error: Division by zero. Please restart the calculation.')
                    return
                result = result % numbers[i]
                calculation_result += f' % {numbers[i]}'

        calculation_result += ' = {}'.format(result)
        print('Result:', calculation_result)

        #Next calculation
        while True:
            next_calculation = input('Do you want to perform another calculation? (Y/N): ')
            if next_calculation.upper() == 'Y':
                break
            elif next_calculation.upper() == 'N':
                print('Thank you for using this calculator!')
                return
            else:
                print('Invalid input. Please choose Y or N.')

calculate()

#Keep up the good works!
