# -*- coding: utf-8 -*-
"""project2_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/150MvT0udrheQiWoJ5s6KS1gU2fcU6gIu
"""

def add(x, y):
    return x + y

def sub(x, y):
    return x - y

def mul(x, y):
    return x * y

def div(x, y):
    if y == 0:
        return "Error: Division by zero is not allowed"
    return x / y

def mod(x, y):
    return x % y

def calculate_expression(expression):
    try:
        expression = expression.replace("^", "**")
        result = eval(expression)
        return result
    except ZeroDivisionError:
        return "Error: Division by zero is not allowed"
    except Exception as e:
        return f"Error: Invalid expression ({str(e)})."

def main():
    print("Enter 'A' for Addition(+)")
    print("Enter 'S' for Subtraction(-)")
    print("Enter 'M' for Multiplication(*)")
    print("Enter 'D' for Division(/)")
    print("Enter 'MOD' for Modulo(%)")
    print("Enter 'EXP' to input a full expression (e.g., (1+2)*3)")

    while True:
        calculator = input("Enter Choice (A, S, M, D, MOD, EXP): ").upper()

        if calculator in ('A', 'S', 'M', 'D', 'MOD'):
            try:
                num_1 = float(input('Enter first number: '))
                num_2 = float(input('Enter second number: '))
            except ValueError:
                print("Invalid input. Please enter a number")
                continue

            if calculator == 'A':
                print('Result:', num_1, '+', num_2, '=', add(num_1, num_2))
            elif calculator == 'S':
                print('Result:', num_1, '-', num_2, '=', sub(num_1, num_2))
            elif calculator == 'M':
                print('Result:', num_1, '*', num_2, '=', mul(num_1, num_2))
            elif calculator == 'D':
                print('Result:', num_1, '/', num_2, '=', div(num_1, num_2))
            elif calculator == 'MOD':
                print('Result:', num_1, '%', num_2, '=', mod(num_1, num_2))
        elif calculator == 'EXP':
            expression = input('Enter the full mathematical expression (e.g., (1+2)*3): ')
            result = calculate_expression(expression)
            print('Result:', result)
        else:
            try:
                result = calculate_expression(calculator)
                print('Result:', result)
            except:
                print("Invalid Input")

        next_calculation = input("Let's do next calculation? (yes/no): ").lower()
        if next_calculation == "no":
            print('Thank you!')
            break

if __name__ == "__main__":
    main()

