# -*- coding: utf-8 -*-
"""Project 2 (1) - Huỳnh An Ri.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Qo31QSGdmJW3dy5mCnhly2Oi33cHoFq
"""

# Define the calculation using eval fomular
def calculator():
    expression = input('Enter a expression that you want to perform:').strip() # get input from user
    result = eval(expression) # perform the calculation by eval fomular
    print(f"The result of '{expression}' is: '{result}'")
    again() # Do you want to take another expression?

# "Do you want to perform another expresion?" option for user
def again():
    calculation_again = input('''
    Do you want to perform another expression?
    Please type Y for Yes and N for No:
    ''')
    if calculation_again == 'Y':
        calculator()
    elif calculation_again == 'N':
        print('See you later')
    else:
        print('Invalid syntax')

calculator()

#Guddd job! Keep it up my friend!

