# -*- coding: utf-8 -*-
"""Project 2 (Create a calculator)-checkpoint - Ngân Đỗ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lmnrnz4alzi93mzQTs4QCQliiE9KD74X
"""

def calculator():
  """
  This function implements a basic calculator with four operations, modulo, multiple number pairs, grouping operations, and continuous calculation.
  """
  while True:
    # Get the operation from the user
    operation = input(
      "Enter 'A' for Addition, 'S' for Subtraction, 'M' for Multiplication, 'D' for Division, '%' for Modulo: "
    )

    # Get the first number from the user
    num1 = float(input("Enter first number: "))

    # Get the second number from the user
    num2 = float(input("Enter second number: "))

    # Perform the calculation based on the operation
    if operation == "A":
      result = num1 + num2
    elif operation == "S":
      result = num1 - num2
    elif operation == "M":
      result = num1 * num2
    elif operation == "D":
      if num2 == 0:
        print("Error: Cannot divide by zero.")
        continue
      else:
        result = num1 / num2
    elif operation == "%":
      if num2 == 0:
        print("Error: Cannot calculate modulo by zero.")
        continue
      else:
        result = num1 % num2
    else:
      print("Invalid operation.")
      continue

    # Print the result
    print(f"Result: {result}")

    # Check if the user wants to perform another calculation
    if input("Do you want to perform another calculation? (Y/N): ").upper() == "N":
      break


if __name__ == "__main__":
  calculator()

#Gud job! Keep it up!

