# -*- coding: utf-8 -*-
"""project20 - Phạm Thùy Tiên.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kPEOQcCR62_0c1THS4pWPuFe-QvHd8DN
"""

def evaluate_expression(expression):
    try:
        result = eval(expression)
        return result
    except Exception as e:
        return f"Error: {e}"

def main():
    print("Basic Calculator")
    print("Enter '+' for Addition")
    print("Enter '-' for Subtraction")
    print("Enter '*' for Multiplication")
    print("Enter '/' for Division")
    print("Enter '%' for Modulo")
    print("Enter '(' for Grouping")
    print("Enter ')' for Grouping")
    print("Enter '=' to Calculate")
    print("Enter 'exit' to end the program")


    ongoing_result = None

    while True:
        if ongoing_result is None:
            expression = input("Enter your expression: ")
        else:
            expression = input(f"Enter your expression (ongoing result = {ongoing_result}): ")
            if expression[0] in "+-*/%":
                expression = str(ongoing_result) + expression

        if expression.lower() == 'exit':
            break
        elif expression == '=':
            continue

        # Calculate the result
        result = evaluate_expression(expression)

        if isinstance(result, str) and result.startswith("Error"):
            print(result)
            ongoing_result = None
        else:
            print(f"Result: {result}")
            ongoing_result = result

if __name__ == "__main__":
    main()