# -*- coding: utf-8 -*-
"""challenge - Nghị Trần.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v9K6HeEBOwFDZF-DUPR-MMT1LsFN28ky
"""

def add_numbers(numbers):
    result = 0
    for num in numbers:
        result += num
    return result

def subtract_numbers(numbers):
    result = numbers[0]
    for num in numbers[1:]:
        result -= num
    return result

def multiply_numbers(numbers):
    result = 1
    for num in numbers:
        result *= num
    return result

def divide_numbers(numbers):
    result = numbers[0]
    for num in numbers[1:]:
        result /= num
    return result

operation = input("Choose one operation (+, -, x, /): ")

numbers = [float(num) for num in input("Enter two or more numbers separated by spaces: ").split()]

if operation == '+':
    result = add_numbers(numbers)
elif operation == '-':
    result = subtract_numbers(numbers)
elif operation == 'x':
    result = multiply_numbers(numbers)
elif operation == '/':
    result = divide_numbers(numbers)
else:
    result = "Invalid operation"

print("Result: ", result)
#Nice work!
#Our requirements for the 3rd bonus point require 
# the program able to calculate an expression with different operation, try better next time!