# -*- coding: utf-8 -*-
"""trinh_8554(Project2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ASD86IJsep1YhOzU7Qtr6b-WhC56wUxN
"""

# Project2:
def calculator():
    while True:
        print("Choose your option:")
        print("1. Start Operation")
        print("2. Exit")

        choice = input("Enter your choice: ")

        if choice == "1":
          expression = input("Enter a mathematical expression: ")
          result = eval(expression)
          print(f"Result of this operation is {result}")

          while True:
            print(f"Continue? (1: Yes/n 2:No)")
            continue_choice = input("Enter your choice: ")
            if continue_choice == "2":
                break
            if continue_choice == "1":
                expression1 = input("Enter a mathematical expression: ")
                result = eval(expression1)
                print(f"Result of this operation is {result}")
                print(f"Continue? (1: Yes/n 2:No)")
                continue_choice = input("Enter your choice: ")
            else:
                print("Invalid choice. Please try again.")
                break

        elif choice == "2":
            print("Exit the calculator!")
            break

        else:
            print("Invalid choice. Please try again.")

calculator()