# -*- coding: utf-8 -*-
"""Project2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i6NsKoMya14NcM1yvlDYayspYtjJrZud
"""

def calculator():
    memory = 0
    print("Welcome to the Python Calculator!")
    print("Use 'ans' to refer to the previous result.")
    print("Enter 'q' to quit.")

    while True:
        expression = input("Enter calculation: ")
        if expression.lower() == 'q':
            print("Thank you for using the calculator. Goodbye!")
            break

        # Replace 'ans' with the value in memory
        expression = expression.replace('ans', str(memory))

        try:
            result = eval(expression)
            print(f"Result: {result}")
            memory = result  # Store result in memory
            print(f"Current memory: {memory}")
        except Exception as e:
            print(f"Error: {e}")
            print("Please check your calculation.")

calculator()